M48
; DRILL file {KiCad 9.0.3} date 2025-08-10T23:59:13-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-10T23:59:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X6.68Y-15.0
X6.68Y-20.78
T2
X2.6Y-30.0
X39.4Y-39.4
X50.2Y-10.0
M30
